"""
services/auth_service.py — BUSINESS LOGIC for auth
==================================================

This is where the actual auth logic lives: registration, login, token creation,
refresh (with rotation), logout.

Why a service layer?
--------------------
The endpoints (api/v1/auth.py) should stay THIN: HTTP concerns (status codes,
request parsing) and delegation. The actual logic belongs in a service.
Advantages:
  * Testable without the HTTP layer (unit tests call functions directly).
  * Reusable (e.g. a CLI command could use the same logic).
  * Clearer: an endpoint is 5 lines instead of 50.

────────────────────────────────────────────────────────────────────────────
THE REFRESH FLOW (rotation) — the hardest part
────────────────────────────────────────────────────────────────────────────
1. Login:     Client receives (access, refresh_a). We store refresh_a
              (hashed) with revoked=False in the DB.
2. Access expires. Client sends refresh_a to /refresh.
3. Server:
     a. Verifies the signature of refresh_a (PyJWT).
     b. Looks up the corresponding DB entry via jti (=refresh_token.id).
     c. Checks: revoked=False? expires_at in the future? user still active?
     d. Sets refresh_a revoked=True ("rotation": the old one is dead).
     e. Issues a NEW pair (access, refresh_b) and stores refresh_b.
4. From now on ONLY refresh_b is valid. If an attacker were to steal
   refresh_a and use it, the legitimate client would notice at the next
   /refresh that its token is revoked -> alarm ("token reuse detection").

Simplification in this template:
  We skip the advanced "reuse detection" (blocking ALL of the user's tokens
  on reuse). That is a hardening step that is optional for learning purposes —
  documented in the README under "Erweiterungen" (extensions).
"""

from datetime import UTC, timedelta
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select

from app.core.config import settings
from app.core.security import create_token, decode_token, hash_password, verify_password
from app.models.refresh_token import RefreshToken
from app.models.user import User, UserRole
from app.schemas.auth import TokenPair, UserCreate, UserRead


# Duplicate-email exception: we define it as its own exception so the endpoint
# can catch it specifically and translate it into a clean 409.
class EmailAlreadyExistsError(Exception):
    """A user with this email already exists."""


class InvalidCredentialsError(Exception):
    """Login/refresh failed (wrong data, expired, revoked)."""


# ============================================================================
# 1) REGISTER
# ============================================================================
async def register_user(session: AsyncSession, data: UserCreate) -> User:
    """
    Creates a new user.

    Steps:
      1. Check whether the email already exists -> if so, raise an error.
      2. Hash the password (NEVER store plaintext!).
      3. Build the user object and save it in the DB.

    New users default to role=USER and is_active=True.
    (We create the first admin via SEED_ADMIN_* at startup — see lifespan.)
    """
    # SELECT * FROM users WHERE email = ?  — executed asynchronously.
    existing = await session.exec(select(User).where(User.email == data.email))
    if existing.first() is not None:
        raise EmailAlreadyExistsError(data.email)

    user = User(
        email=data.email,
        hashed_password=hash_password(data.password),
        full_name=data.full_name,
        role=UserRole.USER,
        is_active=True,
    )
    session.add(user)
    await session.commit()
    # refresh() reloads the fields generated by the DB (id, created_at, ...).
    await session.refresh(user)
    return user


# ============================================================================
# 2) LOGIN (authenticate + issue a token pair)
# ============================================================================
async def authenticate(session: AsyncSession, email: str, password: str) -> User:
    """
    Checks email + password. Returns the user if correct.
    Fails -> InvalidCredentialsError.

    IMPORTANT (security): on a failed login we do NOT reveal WHETHER the email
    exists — the error message is always the same ("Ungültige Anmeldedaten").
    Otherwise an attacker could find out by trial and error which emails are
    registered (user enumeration).
    """
    user = (await session.exec(select(User).where(User.email == email))).first()
    # Careful: user can be None. In that case we do not call verify_password
    # but raise immediately — and we do it so that the response is identical
    # to the "wrong password" case.
    if user is None or not verify_password(password, user.hashed_password):
        raise InvalidCredentialsError()
    if not user.is_active:
        raise InvalidCredentialsError()
    return user


async def issue_token_pair(session: AsyncSession, user: User) -> TokenPair:
    """
    Issues an (access, refresh) pair and stores the refresh token.

    Called both at login and at refresh (DRY).
    """
    # --- Access token: short, contains ONLY the user ID and the type. ---
    access = create_token(
        subject=user.id,
        token_type="access",
        expires_delta=timedelta(minutes=settings.access_token_expire_minutes),
    )

    # --- Refresh token: long. We first create the token ID (jti), then
    #     the JWT, hash it for the DB and insert a row. ---
    refresh_record = RefreshToken(
        user_id=user.id,
        # Hash is set below, as soon as we have the JWT.
        token_hash="",  # placeholder, overwritten right away
        expires_at=_refresh_expiry(),
    )
    # refresh_record.id has already been populated by default_factory=uuid.uuid4.
    refresh_jwt = create_token(
        subject=user.id,
        token_type="refresh",
        expires_delta=timedelta(days=settings.refresh_token_expire_days),
        extra_claims={"jti": str(refresh_record.id)},
    )
    # Store the hash OF the JWT string, not the JWT itself.
    refresh_record.token_hash = hash_password(refresh_jwt)

    session.add(refresh_record)
    await session.commit()

    return TokenPair(
        access_token=access,
        refresh_token=refresh_jwt,
        user=UserRead.model_validate(user),
    )


def _refresh_expiry():
    """Helper: the refresh token's expiry timestamp as a datetime."""
    from datetime import datetime
    from datetime import timedelta as _td

    return datetime.now(UTC) + _td(days=settings.refresh_token_expire_days)


# ============================================================================
# 3) REFRESH (new pair + rotation of the old one)
# ============================================================================
async def refresh_token_pair(session: AsyncSession, refresh_jwt: str) -> TokenPair:
    """
    Exchanges a refresh token for a new pair (rotation).

    For the steps see the module docstring (THE REFRESH FLOW).
    """
    # --- 1. Decode the JWT (verifies signature + expiry) ---
    try:
        payload = decode_token(refresh_jwt)
    except Exception as e:  # jwt.InvalidTokenError + subclasses
        raise InvalidCredentialsError() from e

    # --- 2. Check the type: an access token must NOT work here ---
    if payload.get("type") != "refresh":
        raise InvalidCredentialsError()

    # --- 3. Extract the jti (token ID) and load the DB entry ---
    jti = payload.get("jti")
    if not jti:
        raise InvalidCredentialsError()
    record = await session.get(RefreshToken, UUID(jti))
    if record is None:
        raise InvalidCredentialsError()

    # --- 4. Compare the hash (does the token belong to this jti?) ---
    # Even with the same jti: does the hash match? (Defense in case the jti
    # leaked but the real JWT did not.)
    if not verify_password(refresh_jwt, record.token_hash):
        raise InvalidCredentialsError()

    # --- 5. Check status: revoked? expired? user active? ---
    if record.revoked:
        raise InvalidCredentialsError()
    # expires_at is already checked during decode (exp claim). We additionally
    # check the DB value in case someone messes with the DB by hand.
    #
    # Robustness: some DBs (e.g. SQLite) return timezone-aware datetimes as
    # "naive" values. We normalize both sides to UTC so the comparison never
    # crashes with "offset-naive vs offset-aware".
    from datetime import datetime

    def _to_aware_utc(dt: datetime) -> datetime:
        if dt.tzinfo is None:
            return dt.replace(tzinfo=UTC)
        return dt.astimezone(UTC)

    if _to_aware_utc(record.expires_at) < datetime.now(UTC):
        raise InvalidCredentialsError()

    user = await session.get(User, record.user_id)
    if user is None or not user.is_active:
        raise InvalidCredentialsError()

    # --- 6. ROTATION: revoke the old token ---
    record.revoked = True
    session.add(record)
    await session.commit()

    # --- 7. Issue a new pair ---
    return await issue_token_pair(session, user)


# ============================================================================
# 4) LOGOUT (revoke the refresh token)
# ============================================================================
async def logout(session: AsyncSession, refresh_jwt: str | None) -> None:
    """
    Invalidates the refresh token (revoked=True).

    Access tokens cannot be revoked (stateless!). But they do expire
    automatically after access_token_expire_minutes — which is precisely why
    they are so short. Refresh tokens are long, which is why logout matters.
    """
    if not refresh_jwt:
        return  # nothing to do

    try:
        payload = decode_token(refresh_jwt)
    except Exception:
        return  # invalid token -> silently ignore (idempotent)

    if payload.get("type") != "refresh":
        return

    jti = payload.get("jti")
    if not jti:
        return
    record = await session.get(RefreshToken, UUID(jti))
    if record is not None and not record.revoked:
        record.revoked = True
        session.add(record)
        await session.commit()
