"""
schemas/research.py — Pydantic input/output for research projects
=================================================================

As with the user model (see the models/user.py comment), we separate:
    model (DB form)  vs.  schema (API form).

ResearchCreate: just the question — everything else (id, thread_id, status,
...) is generated by the server. Never accept fields from the client that
must be trusted (otherwise a client could simply wish for status="done").
"""

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SourceOut(BaseModel):
    """A cited source from the web search."""

    title: str
    url: str
    snippet: str = ""


class ResearchCreate(BaseModel):
    """POST /research — body for creating a new research run."""

    question: str = Field(min_length=3, max_length=50000, description="Forschungsfrage")
    # Stage 5: follow-up? Then the new question runs in the SAME LangGraph
    # thread as the original research (the agent "remembers").
    followup_of: UUID | None = None
    # Compact conversation history (Q/A pairs) as context — the client builds
    # it from the chat. It is presented to supervisor + synthesizer in the prompt.
    context_summary: str | None = Field(default=None, max_length=8000)
    # Conversation this question belongs to (Google AI Studio model).
    # None -> new conversation (title = question).
    conversation_id: UUID | None = None
    # Phase 2: "quick" (default) or "deep" (long-form report).
    depth: Literal["quick", "deep"] = "quick"
    # Citation style for deep reports.
    citation_style: Literal["apa", "ieee", "plain"] | None = None

    @field_validator("followup_of", "conversation_id", "context_summary", mode="before")
    @classmethod
    def empty_str_to_none(cls, v: Any) -> Any:
        """Safely convert empty strings (e.g. from form fields) to None."""
        if v == "" or v is None:
            return None
        return v


class ResearchUpdate(BaseModel):
    """PATCH /research/{id} — rename the conversation."""

    title: str = Field(min_length=1, max_length=200, description="Neuer Titel (leer vermeiden)")


class UsageOut(BaseModel):
    """Token usage of a run."""

    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    llm_calls: int = 0


class ResearchProjectOut(BaseModel):
    """Output of a project (list + detail)."""

    model_config = ConfigDict(frozen=True)  # immutable after construction

    id: UUID
    question: str
    title: str | None = None  # display name; NULL -> question as the title
    conversation_id: UUID | None = None  # associated conversation
    depth: str = "quick"
    citation_style: str | None = None
    outline: dict | None = None  # deep outline (survives reloads)
    chapters: list[Any] | None = None  # fully written deep chapters [{title, content}]
    status: str
    report: str | None = None
    error: str | None = None
    sources: list[Any] | None = None  # {title,url,snippet} dicts; None until the stage-2 run
    usage: UsageOut | None = None
    parent_id: UUID | None = None  # set for follow-ups
    trace: list[Any] | None = None  # execution history (sidepanel)
    thread_id: UUID
    created_at: datetime
    updated_at: datetime


class ConversationOut(BaseModel):
    """A conversation (chat) for the history list."""

    model_config = ConfigDict(frozen=True)

    id: UUID
    title: str
    created_at: datetime
    updated_at: datetime
    message_count: int = 0
    total_tokens: int = 0
    last_question: str | None = None


class ConversationDetail(ConversationOut):
    """Conversation including all messages (chronological)."""

    messages: list[ResearchProjectOut] = []


class ConversationUpdate(BaseModel):
    """PATCH /conversations/{id} — rename the conversation."""

    title: str = Field(min_length=1, max_length=200)




class ResearchAdminOut(BaseModel):
    """Admin view: like ResearchProjectOut, plus the owner's email."""

    model_config = ConfigDict(frozen=True)

    id: UUID
    question: str
    status: str
    user_email: str
    usage: UsageOut | None = None
    parent_id: UUID | None = None
    created_at: datetime
